export var jackets = [
  {
    id: 1,
    name: "RainyDays Turquoise",
    price: 1699,
    imageURL: "../images/turquois2.jpg",
    color: "Turqouise",
    inStock: true,
  },
  {
    id: 2,
    name: "RainyDays Black",
    price: 1999,
    imageURL: "../images/black2.jpg",
    color: "Black",
    inStock: true,
  },
  {
    id: 3,
    name: "RainyDays Red",
    price: 1250,
    imageURL: "../images/red2.jpg",
    color: "Red",
    inStock: false,
  },
  {
    id: 4,
    name: "RainyDays Blue",
    price: 2469,
    imageURL: "../images/turquois2.jpg",
    color: "Blue",
    inStock: true,
  },
  {
    id: 5,
    name: "RainyDays Teal",
    price: 2199,
    imageURL: "../images/turquois2.jpg",
    color: "Teal",
    inStock: true,
  },
  {
    id: 6,
    name: "RainyDays Burgundy",
    price: 1100,
    imageURL: "../images/red2.jpg",
    color: "Burgundy",
    inStock: false,
  },
  {
    id: 7,
    name: "RainyDays Midnight",
    price: 1650,
    imageURL: "../images/black2.jpg",
    color: "Midnight Black",
    inStock: true,
  },
  {
    id: 8,
    name: "RainyDays SkyBlue",
    price: 2800,
    imageURL: "../images/turquois2.jpg",
    color: "Sky Blue",
    inStock: true,
  },
];
