export var jackets = [
  {
    id: 1,
    name: "Jacket 1",
    price: 1500,
    imageURL: "../images/turquois2.jpg",
    color: "Turqouise",
    inStock: true,
  },
  {
    id: 2,
    name: "Jacket 2",
    price: 1999,
    imageURL: "../images/black2.jpg",
    color: "Black",
    inStock: true,
  },
  {
    id: 3,
    name: "Jacket 3",
    price: 1230,
    imageURL: "../images/red2.jpg",
    color: "Red",
    inStock: true,
  },
  {
    id: 4,
    name: "Jacket 4",
    price: 2469,
    imageURL: "../images/turquois2.jpg",
    color: "Turquoise",
    inStock: true,
  },
  {
    id: 5,
    name: "Jacket 5",
    price: 2111,
    imageURL: "../images/turquois2.jpg",
    color: "Turquoise",
    inStock: true,
  },
  {
    id: 6,
    name: "Jacket 6",
    price: 1532,
    imageURL: "../images/red2.jpg",
    color: "Red",
    inStock: true,
  },
  {
    id: 7,
    name: "Jacket 7",
    price: 1642,
    imageURL: "../images/black2.jpg",
    color: "Black",
    inStock: false,
  },
  {
    id: 8,
    name: "Jacket 8",
    price: 2521,
    imageURL: "../images/turquois2.jpg",
    color: "Turqouise",
    inStock: true,
  },
];
